services:
  # Servicio de tu aplicación .NET
  nutritional-kitchen: 
    image: stephaniheredia/microservicio-nutritional-kitchen:v5
    container_name: nutritional-kitchen
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=nutritionalKitchen;Username=postgres;Password=password
      - RabbitMqSettings__Host=rabbitmq
      - RabbitMqSettings__UserName=storeUser
      - RabbitMqSettings__Password=storeUserPassword
      - RabbitMqSettings__VirtualHost=/
      - Sentry__Dsn=https://24140945404144a56e3a71912109a2b5@o4509306989248512.ingest.us.sentry.io/4509306991542272
      - Sentry__SendDefaultPii=true
      - Sentry__MaxRequestBodySize=Always
      - Sentry__MinimumBreadcrumbLevel=Debug
      - Sentry__MinimumEventLevel=Warning
      - Sentry__AttachStackTrace=true
      - Sentry__Debug=true
      - Sentry__DiagnosticLevel=Error
    ports:
      - 5075:5075  
    depends_on:
      - postgres-db
    networks:
      - nur-network
      - kong-net
  # Servicio de la base de datos postgresql
  postgres-db: 
    image: stephaniheredia/nutritionalkitchendb:v4
    container_name: postgres-db
    environment:
      - POSTGRES_DB=nutritionalKitchen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password 
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nutritionalKitchen"]
      interval: 10s
      retries: 5
      start_period: 20s
    networks:
      - nur-network 

networks:
  nur-network:
    external: true  
  kong-net:
    external: true  

volumes:
  postgres_data: 
