// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutritionalKitchen.Infrastructure.DomainModel;

#nullable disable

namespace NutritionalKitchen.Infrastructure.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20250705112519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Joseco.Outbox.Contracts.Model.OutboxMessage<NutritionalKitchen.Domain.Abstractions.DomainEvent>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outboxId");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlationId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processedOn");

                    b.Property<string>("SpanId")
                        .HasColumnType("text")
                        .HasColumnName("spanId");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("traceId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outboxMessage", "outbox");
                });

            modelBuilder.Entity("NutritionalKitchen.Domain.KitchenTask.KitchenTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Kitchener")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Kitchener");

                    b.Property<DateTime>("PreparationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PreparationDate");

                    b.HasKey("Id");

                    b.ToTable("KitchenTask", (string)null);
                });

            modelBuilder.Entity("NutritionalKitchen.Domain.Label.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Address");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("ContractId");

                    b.Property<DateTime>("DeliberyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeliberyDate");

                    b.Property<Guid>("DeliberyId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeliberyId");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Detail");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpirationDate");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProductionDate");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Label", (string)null);
                });

            modelBuilder.Entity("NutritionalKitchen.Domain.Package.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("LabelId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Package", (string)null);
                });

            modelBuilder.Entity("NutritionalKitchen.Domain.PreparedFood.PreparedFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Detail");

                    b.Property<Guid>("IdKitchenTask")
                        .HasColumnType("uuid")
                        .HasColumnName("IdKitchenTask");

                    b.Property<Guid>("IdRecipePreparation")
                        .HasColumnType("uuid")
                        .HasColumnName("IdRecipePreparation");

                    b.Property<Guid?>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("LabelId");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<string>("Recipe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Recipe");

                    b.Property<DateTime>("RecipePreparationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RecipePreparationDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("PreparedFood", (string)null);
                });

            modelBuilder.Entity("NutritionalKitchen.Domain.RecipePreparation.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("NutritionalKitchen.Domain.RecipePreparation.RecipePreparation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Detail");

                    b.Property<string>("MealTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MealTime");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<DateTime>("PreparationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PreparationDate");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecipeId");

                    b.HasKey("Id");

                    b.ToTable("RecipePreparation", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
